### PR TITLE
Fail CI if repo is in dirty state after bin/update_readme

### PR DESCRIPTION
**Pull request by bocharsky-bw**
This will help us to catch inconsistence in README on CI level. No more missing call of `bin/update_readme`!

The build should be green after #171 is merged

### CODE REVIEW

**Comment by weaverryan** [comment]
It’s merged! Should we rebase to verify the green build?

**Comment by bocharsky-bw** [comment]
Yeah, I want to do this! Just waiting for tests to actually fail. Unfortunately, Travis Status says that they have slow booting, that's why my builds are pending (yellow) and I don't see it's actually failed right now :/

**Comment by larzuk91** [comment]
They indeed failed

**Comment by bocharsky-bw** [comment]
I think this one is ready now! I merged master and now tests should pass because we fixed dirty state in master

**Comment by weaverryan** [comment]
Thanks! Awesome idea!

**Pull request merged**
