### PR TITLE
New clients added

### PR DESCRIPTION
**Pull request by luchianenco**
Another portion of clients: Salesforce, Zendesk, Strava, Uber, Unsplash, PSN, Mollie are added

### CODE REVIEW

**Comment by weaverryan** [comment]
Ahh... so cool! You rock @luchianenco! Check out our clients list now - https://github.com/knpuniversity/oauth2-client-bundle#step-1-download-the-client-library - 35! Woo!

**Comment by luchianenco** [comment]
thanks ;) 
many providers are a bit outdated...do not support ResourceOwnerInterfacer

**Comment by weaverryan** [comment]
Many in our list are outdated? Or many other client libraries are outdated (so we can't add them)?

**Comment by luchianenco** [comment]
Many client libraries doesn't support ResourceOwnerInterface and therefore we cannot use them as I understand.

**Comment by weaverryan** [comment]
Hmm, yea that makes sense -we require them to return that. Well, probably in those cases, those libraries aren't very used anyways :)

**Comment by luchianenco** [comment]
Some of them, what I would like to add in the first row are Envato, MeetUp, Reddit, Twitch and some others that have really big usage...there are many also that we can add but as I understand they are not so popular.

**Comment by weaverryan** [comment]
Hmm. Yea, I looked at a few of those. They're indeed implemented incorrectly - e.g. https://github.com/tpavlek/oauth2-twitch/blob/ead8e17d393610b35d06f6e42723a75590833a3c/src/Provider/Twitch.php#L130 should return a `ResourceOwnerInterface` (https://github.com/thephpleague/oauth2-client/blob/a887c33ff02ec7f92029903e9e7e0fc5a1c52583/src/Provider/AbstractProvider.php#L742), but it does not. 

That's a bug in their code. So, to support these, the libraries themselves would need to be improved, or replaced with new libs :/

**Pull request merged**
