### PR TITLE
Allow installing the new OAuth client 2.x in dependencies

### LINKED ISSUE #48: OAuth2 client libraries like Facebook needs "league/oauth2-client": "^2.0" to be installed!
I would like to switch to this library from HWIOAuthBundle (we like so much Guard 👍), but client libraries like Facebook, Github, Instagram, Google, Linkedin, Bitbucket (and maybe others...) have a required dependency with `"league/oauth2-client": "^2.0"` that's locked at the `"league/oauth2-client": "^1.0"` version in this bundle. How we can resolve the issue?

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Fix #48

### CODE REVIEW

**Comment by weaverryan** [comment]
Um... so the tests do pass... but all the runs in the test matrix use some version of 1.x of the library...  (you can see it in the `composer update` line in travis). I'm not sure exactly why... I would expect it to grab 2.x on a fresh composer update...

**Comment by bocharsky-bw** [comment]
Yeah, I see... I'm trying to install dependencies locally to see if it grab new version - maybe it's just due to the Travis cache

**Comment by bocharsky-bw** [comment]
The new version installation is suppressed by the `league/oauth2-facebook` dependency

**Comment by bocharsky-bw** [comment]
Now the new versions 2.x were installed on Travis for OAuth client and facebook

**Comment by weaverryan** [comment]
Of *course*!!! Brilliant! And tests still pass! Tagging a new version now!

**Pull request merged**
