### PR TITLE
Changed provider link as current one returned 404 error

### PR DESCRIPTION
**Pull request by maciekpaprocki**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
I don't much like refer to the list of files, but looks like it's the best option here 👍

**Comment by bocharsky-bw** [comment]
But what do you think about referring to the https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/league.md instead? It has one more link to the third-party providers inside

**Comment by maciekpaprocki** [comment]
Links on this page to third party don't work either, but probably good
shout.

I sent pull request to them too.

Feel like an asshole for doing only commits with link change and getting
everyone notified.

Thanks for quick feedback.
Maciej

Best regards
Maciej Paprocki

mobile: 07884432073
email: maciekpaprocki@gmail.com
www: paprocki.co.uk

**Comment by bocharsky-bw** [comment]
@maciekpaprocki Yep, it's a bit confusing when links change :/

Btw, your PR will be declined. The reason is that broken links on GitHub are working for their website: http://oauth2-client.thephpleague.com/ . So we should use links to this website instead of GitHub. And yes, I know, they have not a perfect solution for building links on this website, but we can't do anything with it. So let's use this one:
http://oauth2-client.thephpleague.com/providers/league/

**Comment by maciekpaprocki** [comment]
Yes, I agree, I just sent an update. 

That's weird that they have such a problem. Surely it's better to look on it on their docs page either way. 

Thanks

**Comment by bocharsky-bw** [comment]
👍

**Comment by bocharsky-bw** [comment]
Thank you @maciekpaprocki for the discussion here and this useful fix!

**Pull request merged**
