### PR TITLE
Typo in README

### PR DESCRIPTION
**Pull request by johnnypeck**
Change "are" to "as."

### CODE REVIEW

**Comment by weaverryan** [comment]
Awesome, thanks :)

**Comment by weaverryan** [comment]
And btw, this isn't quite useable yet, but will be in an alpha, useable state pretty soon :)

**Comment by okwinza** [comment]
@weaverryan dont wanna open up a new issue for this so i just wanted to let u know about the most annoying bug in HWIOauthBundle in case you've missed it: hwi/HWIOAuthBundle#149

It gave me a lot of headache back then so would be nice to avoid it in this bundle.
Cheers!

**Comment by weaverryan** [comment]
@okwinza ah, thanks - I *am* actually going to open an issue so that I don't forget about that :).

See #2

**Pull request merged**
