### PR TITLE
Updating Guard docs for Sf4 support

### LINKED ISSUE #77: The guard example documentation should be updated
On Symfony 4.0, if we extends your GuardAuthenticator, we have to implements more method like `start` or `supports`.

For example with this part:

```php
    public function getCredentials(Request $request)
    {
        if ($request->getPathInfo() != '/connect/facebook/check') {
            // don't auth
            return;
        }

        return $this->fetchAccessToken($this->getFacebookClient());
    }
```

The request path check should be done on the `supports` method.

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #77

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@weaverryan does this not break it for < 4.0 where supports is not checked by symfony?

**Comment by bocharsky-bw** [comment]
It does... I mean, this method just won't be called. But we need to keep things up-to-date with the latest version and keeping different docs for several supported versions would be overkill here I think.

Do you think we need some kind of note here?

**Comment by alexander-schranz** [comment]
@bocharsky-bw maybe something like:

// When using Symfony < 4.0 uncomment the following code:
// if (!$this->supports()) {
//    return;
// }

**Comment by bocharsky-bw** [comment]
Hm, I like it! You want to add it below the `// this method is only called if supports() returns true`, right?

Would you like to create a PR?

**Comment by alexander-schranz** [comment]
@bocharsky-bw its here: https://github.com/knpuniversity/oauth2-client-bundle/pull/97

**Pull request merged**
