### PR TITLE
VK.com Provider added

### PR DESCRIPTION
**Pull request by okwinza**
For #7

This new custom providers system is pure awesomeness! Thanks, Ryan!

EvE Online provider is en route aswell.

### CODE REVIEW

**Comment by okwinza** [comment]
Not sure why travis failed. Seems like some unrelated issue with its config.

**Comment by okwinza** [comment]
Ok its green now.

**Comment by fatihkahveci** [comment]
:+1:

**Comment by weaverryan** [comment]
Looks awesome - thank you!

**Comment by weaverryan** [comment]
@okwinza I actually just reverted this - it looks like https://github.com/j4k/oauth2-vkontakte is not compatible with `thephpleague/oauth2-client` 2.0 - the VK composer.json requires `~0.5` of that library.

**Comment by weaverryan** [comment]
Sorry, rather I meant version 1.0, not 2.0 :) - but the point remains: the lib is built for 0.x of the OAuth lib, not 1.x

**Comment by okwinza** [comment]
oh snap, sorry, i'll just write my own then.
Btw take a look at my #17 it should be g2g

**Comment by okwinza** [comment]
ok its not g2g, gonna rebase in few sec

**Pull request merged**
