### PR TITLE
VKontakte provider added

### PR DESCRIPTION
**Pull request by fatihkahveci**
for issue #7 VKontakte provider added.

### CODE REVIEW

**Comment by okwinza** [comment]
That lib you're trying to integrate is still not compatible with `thephpleague/oauth2-client` 2.0 as it requires `^1.4` in composer.json

See #10

**Comment by fatihkahveci** [comment]
@okwinza ups :/ . I can't find compatible with thephpleague/oauth2-client any VK provider. I guesse i will tackle that asap.

**Comment by weaverryan** [comment]
I just re-checked things because #46 was opened - it looks like the library has been updated since June last year: https://github.com/j4k/oauth2-vkontakte/commit/369194539123d6f52476eba34965611d8e270643

So, I think we *can* merge this now.

**Comment by fatihkahveci** [comment]
@weaverryan I just fix conflict we can merge now 😃

**Comment by okwinza** [comment]
@weaverryan wow how did i miss that. In this case we definitely can merge this. :+1:

**Comment by weaverryan** [comment]
Very fast - thank you @fatihkahveci! Already tagged 1.7.0!

**Pull request merged**
